[WIP] HF Hub Integration
facebookresearch/mbrl-lib pull request #171
Opened 2022-12-01 22:55 UTC by natolambert

Working towards closing #169

Things to do (roughly):
* Verify base functionality,
* Colab example for loading / saving / visualizing models,
* Upload pretrained models to hub from @luisenp.

2022-12-02 14:39 UTC, Wauplin reviewed
Hi @natolambert , really nice implementation ! :)
I left a comment about the `log` directory. I think it should be deleted from the Hub before uploading otherwise you can end up with a messy foler. Other than that, looks good :+1:

2022-12-02 14:39 UTC, Wauplin commented on mbrl/util/huggingface.py
> +            shutil.rmtree(repo_logdir)
Here `repo_logdir` is a tmp dir (at least when called from `package_to_hub`.
So deleting it locally will not delete it on the Hub. A possibility is to use `delete_folder` to delete the logs folder on the Hub before uploading the new one.

2022-12-02 14:39 UTC, Wauplin commented on mbrl/util/huggingface.py
> +    repo_url = HfApi().create_repo(
(nit) for consistency with `upload_folder` calls, I would import `create_repo` directly from `huggingface_hub`.
If not called with any parameter, using `HfApi().` is not needed.

2022-12-02 14:39 UTC, Wauplin commented on mbrl/util/huggingface.py
> +    repo_url = HfApi().create_repo(
(nit) same as above about `HfApi`

2022-12-06 01:39 UTC, natolambert commented
WIP [Colab](https://colab.research.google.com/drive/158ZJ0nB0aJkml_yVpoUHSqQlPE-glK1G?usp=sharing) to showcase this workflow.

2022-12-06 16:17 UTC, luisenp requested changes
Thanks @natolambert! I left a bunch of comments, but mostly pedantic stuff about formatting and docstrings. I'm not too familiar with HF Hub, so most of the rest LGTM.  However, I noticed that `package_hub` only receives a `Model`, even though we also have algorithms that require a trained `Agent` (e.g., MBPO, and eventually Dreamer). This seems like a potential issue?

Also, is the expectation that should be able to download saved model/agents from the hub and run them on our example scripts?

2023-04-11 21:56 UTC, closed without merging