Training browser
facebookresearch/mbrl-lib pull request #77
Opened 2021-04-28 19:28 UTC by a3ahmad

## Types of changes

Adds a simple browser to chart training results from multiple runs

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

Adds a quick and easy way to browse/compare results

## How Has This Been Tested (if it applies)

I ran a few different training runs, with different algorithms and use this to compare them

## Checklist

- [ ] The documentation is up-to-date with the changes I made.
- [X] I have read the [**CONTRIBUTING**](../../CONTRIBUTING.md) document and completed the CLA (see **CONTRIBUTING**).
- [ ] All tests passed, and additional code has been covered with new tests.

2021-04-28 19:55 UTC, luisenp commented
@a3ahmad This looks potentially pretty nice! Would you mind adding some brief instruction on how to run so that I can play around with it before making any suggestions?

Also, probably the best place to put this  would be in the `diagnostics` folder (we might change later this folder to something like "visualizations").

2021-04-28 20:26 UTC, a3ahmad commented
Sure, just run it with 'python training_browser.py' (you will need PyQt5 and PyQtChart installed -- pip and conda provide it)

You'll see a full size window with a (dockable) pane on the left listing all the available experiments in a table. Click on each to chart their results (or shift-click to select/overlay multiple results).  The toolbar currently has check-boxes to use a logarithmic axis, and to filter out outliers (I don't like the current implementation as it removes the points, rather than just rescale the Y axis)

2021-04-28 23:41 UTC, a3ahmad commented
Ok, I've moved it to diagnostics.  So now you can run it with:

python -m mbrl.diagnostics.training_browser

I run it from the root mbrl_lib folder and it will infer current_working_directory/exp. Alternatively you can run:

python -m mbrl.diagnostics.training_browser --experiments [path to the experiment folder]

2021-04-29 14:52 UTC, luisenp commented
This is awesome @a3ahmad, thanks a lot! A couple of suggestions:

- Rather than reading the experiment description from the path, it would be better to read the yaml config generated by Hydra, which is saved in `.hydra/config.yaml`, under the same folder that has `results.csv`. There we can get some of the same information (env, algorithm, experiment_name) except the date/time; we can also get other info like the seed used. This is to avoid users that have a different folder structure to get weird info in the browser. For example, when you run an algorithm with `--multirun` in Hydra, you'll get an extra folder with an integer index, and in this case the current browser code crashes. I could potentially add some date info in a metadata file (or maybe save it in the config) to keep it available for the browser, if you think that's useful. 
- Can we add another tab to the browser that plots the mean and standard deviation plot over the different results, as shown below? We can probably pre-compute the data frame created in line line 117, and the serve depending on the index row clicked. This makes sense for things that have the same experiment_name+env+algorithm config+datetime though.

![image](https://user-images.githubusercontent.com/4759586/116569574-8358c500-a8d7-11eb-8ec2-3d602f74f586.png)

Would you be OK with adding this changes?

2021-04-29 14:54 UTC, luisenp commented
BTW, `black` was updated recently which broke the CI tests. I've already updated `master`, so you can just rebase and force push here.

2021-04-29 15:56 UTC, a3ahmad commented
Those are great suggestions, I’ll get on them

2021-04-29 23:52 UTC, a3ahmad commented
@luisenp, what kind of rolling window do you use for the mean/std-dev plots?

2021-04-30 02:36 UTC, luisenp commented
> @luisenp, what kind of rolling window do you use for the mean/std-dev plots?

@a3ahmad For the plot like the one I showed I usually just plot with no smoothing. Just average/std over multiple runs (in the case of that plot it was 10 seeds), for all time steps. We could add the window as an optional argument, seems like a useful feature.

2021-04-30 05:23 UTC, a3ahmad commented
Ohh, I got you. I need to experiment with multiple runs!

2021-05-13 22:05 UTC, luisenp commented
Hi @a3ahmad, thanks again for working on this! I noticed you added a checkbox labeled "Display As Distribution", but currently appears greyed out for me. Is there anything I need to do to enable it?

2021-05-13 23:49 UTC, a3ahmad commented
Oh! You need you multiselect several runs of the same length.

The graph doesn’t look right to me, though. I need to investigate.

2021-05-18 06:00 UTC, a3ahmad commented
Updated to swap from QtCharts to matplotlib. Simplifies code and works better.

2021-05-18 15:26 UTC, luisenp requested changes
This is great, thanks a lot! Left a few minor comments, but this is almost ready from my point of view.

2021-05-18 15:26 UTC, luisenp commented on mbrl/diagnostics/training_browser.py
> +            self.axes.legend()
This is looking great! One comment and I'm not sure if this is awkward to add. Is there any way we can have the user choose labels for the legend of the aggregated plot, and same for xlabel and ylabel?

2021-05-18 15:26 UTC, luisenp commented on mbrl/diagnostics/training_browser.py
> +                mean_line = self.axes.plot(time_series, mean_series, label=self.experiment_results[rowIndex])
Is there any way to have a button that has the option to save the plot to some folder? Even something as simple as a showing a text box for the user to write the path and use `matplotlib` to save it somewhere.

2021-05-18 15:26 UTC, luisenp commented on mbrl/diagnostics/training_browser.py
>  from matplotlib.figure import Figure
One more thing, if you haven't already, can you install https://pre-commit.com/ to run the linter, mypy, etc. automatically?

2021-05-20 12:52 UTC, merged